name: SelfHostedDeploy
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Deploy
        shell: powershell
        run: |
          .\BuildAndCopy.ps1
